// Offline/demo seed used when the API is unreachable (apiStatus === 'demo').
function demoDate(offset = 0) {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  const localDate = new Date(date.getTime() - date.getTimezoneOffset() * 60000);
  return localDate.toISOString().slice(0, 10);
}

function demoDateTime(offset, time) {
  return `${demoDate(offset)}T${time}:00`;
}

export function createDemoState() {
  const today = demoDate(0);
  const tomorrow = demoDate(1);
  const nextWeek = demoDate(7);

  const roles = [
    { id: 'demo-role-admin', name: 'Administrador', permissionIds: [] },
    { id: 'demo-role-lawyer', name: 'Advogado', permissionIds: [] },
    { id: 'demo-role-assistant', name: 'Estagiário', permissionIds: [] },
  ];

  const users = [
    {
      id: 'demo-user-renata',
      name: 'Renata Sampaio',
      email: 'renata@rsadvocacia.demo',
      picture: '',
      roleId: 'demo-role-admin',
      googleCalendarConnected: false,
      googleCalendarDestination: 'agenda principal do Google',
    },
    {
      id: 'demo-user-mariana',
      name: 'Mariana Souza',
      email: 'mariana@rsadvocacia.demo',
      picture: '',
      roleId: 'demo-role-lawyer',
      googleCalendarConnected: false,
      googleCalendarDestination: 'agenda principal do Google',
    },
    {
      id: 'demo-user-lorenzo',
      name: 'Lorenzo dos Reis',
      email: 'lorenzo@rsadvocacia.demo',
      picture: '',
      roleId: 'demo-role-assistant',
      googleCalendarConnected: false,
      googleCalendarDestination: 'agenda principal do Google',
    },
  ];

  const clients = [
    {
      id: 'demo-client-bruno',
      name: 'Bruno Lima',
      email: 'bruno.lima@email.demo',
      phone: '(11) 98888-1200',
      document: '12345678909',
      clientType: 'mensalista',
      notes: 'Cliente com acompanhamento ativo em demanda civel e prazos fatais nesta semana.',
    },
    {
      id: 'demo-client-almeida',
      name: 'Almeida Comercio LTDA',
      email: 'juridico@almeidacomercio.demo',
      phone: '(11) 3777-4400',
      document: '12345678000190',
      clientType: 'mensalista',
      notes: 'Contrato mensal para consultivo empresarial e contencioso trabalhista.',
    },
    {
      id: 'demo-client-ana',
      name: 'Ana Ribeiro',
      email: 'ana.ribeiro@email.demo',
      phone: '(21) 97777-8844',
      document: '98765432100',
      clientType: 'esporadico',
      notes: 'Atendimento pontual em acao indenizatoria.',
    },
  ];

  const processes = [
    {
      id: 'demo-process-bruno',
      number: '1000002-20.2026.8.26.0100',
      clientId: 'demo-client-bruno',
      clientName: 'Bruno Lima',
      description: 'Acao de obrigacao de fazer com pedido de tutela de urgencia.',
      court: '12a Vara Civel de Sao Paulo',
      area: 'Civel',
      status: 'Em andamento',
      owner: 'Mariana Souza',
    },
    {
      id: 'demo-process-almeida',
      number: '0002451-77.2026.5.02.0031',
      clientId: 'demo-client-almeida',
      clientName: 'Almeida Comercio LTDA',
      description: 'Reclamacao trabalhista com audiencia inicial designada.',
      court: '31a Vara do Trabalho de Sao Paulo',
      area: 'Trabalhista',
      status: 'Aguardando despacho',
      owner: 'Renata Sampaio',
    },
    {
      id: 'demo-process-ana',
      number: '0801123-45.2026.8.19.0001',
      clientId: 'demo-client-ana',
      clientName: 'Ana Ribeiro',
      description: 'Acao indenizatoria por danos materiais e morais.',
      court: '5a Vara Civel do Rio de Janeiro',
      area: 'Civel',
      status: 'Ativo',
      owner: 'Mariana Souza',
    },
  ];

  const events = [
    {
      id: 'demo-event-audiencia',
      title: 'Audiencia de conciliacao',
      description: 'Audiencia virtual. Conferir documentos e proposta antes do horario.',
      start: demoDateTime(0, '09:30'),
      end: demoDateTime(0, '10:30'),
      type: 'Audiencia',
      status: 'Confirmado',
      priority: 'Alta',
      clientId: 'demo-client-bruno',
      clientName: 'Bruno Lima',
      processId: 'demo-process-bruno',
      processNumber: '1000002-20.2026.8.26.0100',
      responsible: 'Mariana Souza',
      createdBy: 'Renata Sampaio',
      location: 'Videoconferencia',
      notes: 'Enviar link ao cliente 30 minutos antes.',
      reminderAt: demoDateTime(0, '09:00'),
      completed: false,
    },
    {
      id: 'demo-event-reuniao',
      title: 'Reuniao de alinhamento trabalhista',
      description: 'Revisar documentos de jornada e estrategia para audiencia.',
      start: demoDateTime(1, '14:00'),
      end: demoDateTime(1, '15:00'),
      type: 'Reuniao',
      status: 'Pendente',
      priority: 'Media',
      clientId: 'demo-client-almeida',
      clientName: 'Almeida Comercio LTDA',
      processId: 'demo-process-almeida',
      processNumber: '0002451-77.2026.5.02.0031',
      responsible: 'Renata Sampaio',
      createdBy: 'Lorenzo dos Reis',
      location: 'Escritorio',
      notes: 'Separar contrato social e controles de ponto.',
      reminderAt: demoDateTime(1, '13:30'),
      completed: false,
    },
    {
      id: 'demo-event-tarefa',
      title: 'Conferir documentos do cliente',
      description: 'Checklist de provas antes do protocolo.',
      start: demoDateTime(0, '16:00'),
      end: demoDateTime(0, '16:30'),
      type: 'Tarefa interna',
      status: 'Pendente',
      priority: 'Media',
      clientId: 'demo-client-ana',
      clientName: 'Ana Ribeiro',
      processId: 'demo-process-ana',
      processNumber: '0801123-45.2026.8.19.0001',
      responsible: 'Lorenzo dos Reis',
      createdBy: 'Mariana Souza',
      location: '',
      notes: 'Validar notas fiscais e comprovantes.',
      reminderAt: '',
      completed: false,
    },
  ];

  const deadlines = [
    {
      id: 'demo-deadline-contestacao',
      title: '1000002-20.2026.8.26.0100 - Bruno Lima',
      description: 'Preparar contestacao e documentos para protocolo.',
      date: today,
      status: 'Pendente',
      priority: 'Alta',
      clientId: 'demo-client-bruno',
      clientName: 'Bruno Lima',
      processId: 'demo-process-bruno',
      processNumber: '1000002-20.2026.8.26.0100',
      responsible: 'Mariana Souza',
      createdBy: 'Renata Sampaio',
      notes: 'Conferir procuracao e comprovantes anexos.',
      completed: false,
      elapsedSeconds: 2700,
      timerStartedAt: '',
    },
    {
      id: 'demo-deadline-manifestacao',
      title: '0002451-77.2026.5.02.0031 - Almeida Comercio LTDA',
      description: 'Manifestacao sobre documentos juntados pela parte reclamante.',
      date: tomorrow,
      status: 'Em andamento',
      priority: 'Alta',
      clientId: 'demo-client-almeida',
      clientName: 'Almeida Comercio LTDA',
      processId: 'demo-process-almeida',
      processNumber: '0002451-77.2026.5.02.0031',
      responsible: 'Renata Sampaio',
      createdBy: 'Lorenzo dos Reis',
      notes: 'Revisar holerites e controles de ponto.',
      completed: false,
      elapsedSeconds: 5400,
      timerStartedAt: '',
    },
    {
      id: 'demo-deadline-protocolo',
      title: '0801123-45.2026.8.19.0001 - Ana Ribeiro',
      description: 'Protocolar peticao inicial revisada.',
      date: nextWeek,
      status: 'Protocolar',
      priority: 'Media',
      clientId: 'demo-client-ana',
      clientName: 'Ana Ribeiro',
      processId: 'demo-process-ana',
      processNumber: '0801123-45.2026.8.19.0001',
      responsible: 'Mariana Souza',
      createdBy: 'Renata Sampaio',
      notes: 'Aguardar assinatura final.',
      completed: false,
      elapsedSeconds: 0,
      timerStartedAt: '',
    },
  ];

  const petitions = [
    {
      id: 'demo-petition-bruno',
      clientId: 'demo-client-bruno',
      clientName: 'Bruno Lima',
      processId: 'demo-process-bruno',
      processNumber: '1000002-20.2026.8.26.0100',
      type: 'Contestação',
      adversary: 'Companhia Alfa S/A',
      responsible: 'Mariana Souza',
      driveLink: 'https://drive.google.com/',
      pendingReason: 'Aguardando confirmacao de documentos complementares.',
      area: 'Civel',
      status: 'Pendente',
      createdBy: 'Renata Sampaio',
      createdAt: `${today}T08:30:00`,
      updatedAt: `${today}T11:20:00`,
    },
    {
      id: 'demo-petition-almeida',
      clientId: 'demo-client-almeida',
      clientName: 'Almeida Comercio LTDA',
      processId: 'demo-process-almeida',
      processNumber: '0002451-77.2026.5.02.0031',
      type: 'Contestação',
      adversary: 'Joao Pereira',
      responsible: 'Renata Sampaio',
      driveLink: 'https://drive.google.com/',
      pendingReason: '',
      area: 'Trabalhista',
      status: 'Em andamento',
      createdBy: 'Lorenzo dos Reis',
      createdAt: `${today}T09:00:00`,
      updatedAt: `${today}T13:10:00`,
    },
    {
      id: 'demo-petition-ana',
      clientId: 'demo-client-ana',
      clientName: 'Ana Ribeiro',
      processId: 'demo-process-ana',
      processNumber: '0801123-45.2026.8.19.0001',
      type: 'Petição',
      adversary: 'Beta Seguradora',
      responsible: 'Mariana Souza',
      driveLink: '',
      pendingReason: '',
      area: 'Civel',
      status: 'Protocolar',
      createdBy: 'Renata Sampaio',
      createdAt: `${today}T10:15:00`,
      updatedAt: `${today}T15:40:00`,
    },
  ];

  const prospects = [
    {
      id: 'demo-prospect-carla',
      name: 'Carla Nogueira',
      phone: '(11) 98123-4567',
      email: 'carla.nogueira@email.demo',
      origin: 'Indicação',
      demandType: 'Trabalhista',
      caseDescription: 'Rescisão indireta com verbas atrasadas.',
      responsibleId: 'demo-user-mariana',
      responsibleName: 'Mariana Souza',
      status: 'Em contato',
      priority: 'Alta',
      nextAction: 'Enviar proposta de honorários',
      notes: '',
      lastContact: today,
      convertedClientId: '',
      convertedAt: '',
      interactionsCount: 1,
      createdAt: `${today}T09:00:00`,
      interactions: [
        {
          id: 'demo-interacao-carla-1',
          prospectId: 'demo-prospect-carla',
          type: 'ligacao',
          description: 'Primeiro contato. Cliente interessada.',
          date: `${today}T09:00:00`,
          userId: 'demo-user-mariana',
          userName: 'Mariana Souza',
        },
      ],
    },
    {
      id: 'demo-prospect-pedro',
      name: 'Pedro Antunes',
      phone: '(11) 97654-3210',
      email: 'pedro.antunes@email.demo',
      origin: 'Site',
      demandType: 'Cível',
      caseDescription: 'Ação indenizatória por danos morais.',
      responsibleId: 'demo-user-renata',
      responsibleName: 'Renata Sampaio',
      status: 'Novo',
      priority: 'Media',
      nextAction: 'Agendar reunião inicial',
      notes: '',
      lastContact: '',
      convertedClientId: '',
      convertedAt: '',
      interactionsCount: 0,
      createdAt: `${today}T11:30:00`,
      interactions: [],
    },
  ];

  const lancamentos = [
    {
      id: 'demo-lancamento-honorarios',
      description: 'Honorários iniciais - Bruno Lima',
      type: 'receita',
      category: 'Honorários',
      value: 3500,
      dueDate: nextWeek,
      paymentDate: '',
      status: 'Pendente',
      displayStatus: 'Pendente',
      overdue: false,
      clientId: 'demo-client-bruno',
      clientName: 'Bruno Lima',
      caseId: 'demo-process-bruno',
      caseNumber: '1000002-20.2026.8.26.0100',
      notes: '',
      createdAt: `${today}T08:00:00`,
    },
    {
      id: 'demo-lancamento-software',
      description: 'Assinatura sistema jurídico',
      type: 'despesa',
      category: 'Software',
      value: 240,
      dueDate: today,
      paymentDate: today,
      status: 'Pago',
      displayStatus: 'Pago',
      overdue: false,
      clientId: '',
      clientName: '',
      caseId: '',
      caseNumber: '',
      notes: '',
      createdAt: `${today}T08:10:00`,
    },
  ];

  return {
    permissionGroups: [],
    roles,
    users,
    clients,
    processes,
    events,
    deadlines,
    petitions,
    prospects,
    lancamentos,
    timeEntries: [],
    productivityGoals: users.map((user) => ({
      id: `demo-goal-${user.id}`,
      userId: user.id,
      dailyHours: 6,
      weeklyHours: 30,
      configured: false,
    })),
    currentUser: users[0],
  };
}
