"""
Django settings for jurisagenda project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import dj_database_url
from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _clean_host(value: str) -> str:
    return value.strip().removeprefix("https://").removeprefix("http://").rstrip("/")


def _split_env_hosts(value: str) -> list[str]:
    return [_clean_host(item) for item in value.split(",") if _clean_host(item)]


def _split_env_origins(value: str) -> list[str]:
    return [item.strip().rstrip("/") for item in value.split(",") if item.strip()]


def _env_flag(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _clean_database_url(value: str) -> str:
    parsed = urlsplit(value)
    query = [
        (key, query_value)
        for key, query_value in parse_qsl(parsed.query, keep_blank_values=True)
        if key != "supa"
    ]
    return urlunsplit(
        (
            parsed.scheme,
            parsed.netloc,
            parsed.path,
            urlencode(query),
            parsed.fragment,
        )
    )


def _database_url_from_env() -> str:
    database_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")

    if not database_url:
        raise ImproperlyConfigured(
            "Defina DATABASE_URL com a connection string PostgreSQL. "
            "SQLite nao e mais suportado neste projeto."
        )

    database_scheme = urlsplit(database_url).scheme
    if database_scheme in {"http", "https"}:
        raise ImproperlyConfigured(
            "DATABASE_URL deve ser uma connection string de banco, "
            "como postgresql://usuario:senha@host:5432/banco. "
            "Nao use uma URL https:// de app, dashboard ou API."
        )

    return _clean_database_url(database_url)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = os.getenv("DEBUG")
if _debug_env is None:
    DEBUG = not bool(os.getenv("VERCEL"))
else:
    DEBUG = _debug_env.strip().lower() in {"1", "true", "yes", "on"}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-+g)herdbhyeh+jva+k)qugqi$v1qa^%(4p756636ltfzx_i6ll"
    else:
        raise ImproperlyConfigured("Defina SECRET_KEY nas variaveis de ambiente da Vercel.")

ALLOWED_HOSTS = sorted(
    {
        "127.0.0.1",
        "localhost",
        "agenda-juri.vercel.app",
        "agenda-juri-orcin.vercel.app",
        *(
            _clean_host(host)
            for host in (
                os.getenv("VERCEL_URL", ""),
                os.getenv("VERCEL_PROJECT_PRODUCTION_URL", ""),
            )
            if _clean_host(host)
        ),
        *_split_env_hosts(os.getenv("ALLOWED_HOSTS", "")),
    }
)


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "clientes",
    "processos",
    "agenda",
    "core",
    "usuarios",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jurisagenda.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "jurisagenda.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        _database_url_from_env(),
        conn_max_age=int(os.getenv("DATABASE_CONN_MAX_AGE", "0")),
        conn_health_checks=True,
    )
}

if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].setdefault("prepare_threshold", None)

    require_ssl = _env_flag("DATABASE_SSL_REQUIRE")
    if require_ssl or not DEBUG:
        DATABASES["default"]["OPTIONS"].setdefault("sslmode", "require")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

WHITENOISE_USE_FINDERS = DEBUG

if not DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        }
    }

# CORS/CSRF for the React frontend. Keep this as an explicit allowlist in production.
DEFAULT_REACT_ORIGINS = [
    "https://agenda-juri-orcin.vercel.app",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOWED_ORIGINS = sorted(
    {
        *DEFAULT_REACT_ORIGINS,
        *_split_env_origins(os.getenv("CORS_ALLOWED_ORIGINS", "")),
    }
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-csrftoken",
)

CSRF_TRUSTED_ORIGINS = sorted(
    {
        *CORS_ALLOWED_ORIGINS,
        *_split_env_origins(os.getenv("CSRF_TRUSTED_ORIGINS", "")),
    }
)

CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
