"""
Django settings for jurisagenda project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import dj_database_url
from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env() -> None:
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip().removeprefix("export ").strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]

        os.environ.setdefault(key, value)


_load_local_env()


def _clean_host(value: str) -> str:
    return value.strip().removeprefix("https://").removeprefix("http://").rstrip("/")


def _split_env_hosts(value: str) -> list[str]:
    return [_clean_host(item) for item in value.split(",") if _clean_host(item)]


def _split_env_origins(value: str) -> list[str]:
    return [item.strip().rstrip("/") for item in value.split(",") if item.strip()]


def _env_flag(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _clean_database_url(value: str) -> str:
    parsed = urlsplit(value)
    query = [
        (key, query_value)
        for key, query_value in parse_qsl(parsed.query, keep_blank_values=True)
        if key != "supa"
    ]
    return urlunsplit(
        (
            parsed.scheme,
            parsed.netloc,
            parsed.path,
            urlencode(query),
            parsed.fragment,
        )
    )


def _database_url_from_env() -> str:
    database_url = os.getenv("DATABASE_URL") or os.getenv("POSTGRES_URL")

    if not database_url:
        raise ImproperlyConfigured(
            "Defina DATABASE_URL com a string de conexão PostgreSQL. "
            "SQLite não é mais suportado neste projeto."
        )

    database_scheme = urlsplit(database_url).scheme
    if database_scheme in {"http", "https"}:
        raise ImproperlyConfigured(
            "DATABASE_URL deve ser uma string de conexão de banco, "
            "como postgresql://usuario:senha@host:5432/banco. "
            "Não use uma URL https:// de aplicativo, painel ou API."
        )

    return _clean_database_url(database_url)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = os.getenv("DEBUG")
if _debug_env is None:
    DEBUG = False  # safe default; set DEBUG=true for local dev
else:
    DEBUG = _debug_env.strip().lower() in {"1", "true", "yes", "on"}

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = (  # nosec B105 - dev-only fallback; prod raises ImproperlyConfigured below
            "django-insecure-+g)herdbhyeh+jva+k)qugqi$v1qa^%(4p756636ltfzx_i6ll"
        )
    else:
        raise ImproperlyConfigured(
            "Defina SECRET_KEY nas variaveis de ambiente de producao."
        )

ALLOWED_HOSTS = sorted(
    {
        "127.0.0.1",
        "localhost",
        *_split_env_hosts(os.getenv("ALLOWED_HOSTS", "")),
    }
)


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "clientes",
    "processos",
    "agenda",
    "prazos",
    "peticoes",
    "productivity",
    "prospeccao",
    "financeiro",
    "auditoria",
    "core",
    "usuarios",
    "integrations",
    "ai",
    "meetings",
    "documentos",
    "notificacoes",
    "opcoes",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jurisagenda.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "jurisagenda.wsgi.application"


# Banco de dados
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        _database_url_from_env(),
        conn_max_age=int(os.getenv("DATABASE_CONN_MAX_AGE", "60")),
        conn_health_checks=True,
    )
}

if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].setdefault("prepare_threshold", None)

    require_ssl = _env_flag("DATABASE_SSL_REQUIRE")
    if require_ssl or not DEBUG:
        DATABASES["default"]["OPTIONS"].setdefault("sslmode", "require")


# Validação de senha
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Usuários da aplicação autenticam via Google OAuth (set_unusable_password),
# mas mantemos os validadores padrão para contas administrativas locais.
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internacionalização
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Arquivos estáticos (CSS, JavaScript e imagens)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", str(BASE_DIR / "media")))

WHITENOISE_USE_FINDERS = DEBUG

if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }

# CORS/CSRF para a interface React. Mantenha esta lista explícita em produção.
DEFAULT_REACT_ORIGINS = [
    "https://rs-advocacia.pages.dev",
    "http://localhost",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
FRONTEND_URL = os.getenv("FRONTEND_URL", DEFAULT_REACT_ORIGINS[0]).strip().rstrip("/")

# Sempre False por padrao, mesmo em DEBUG=True: ligar debug local nao deve
# implicar CORS irrestrito em nenhum ambiente (staging incluido). Precisa de
# opt-in explicito via env var.
CORS_ALLOW_ALL_ORIGINS = _env_flag("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = sorted(
    {
        *DEFAULT_REACT_ORIGINS,
        *_split_env_origins(os.getenv("CORS_ALLOWED_ORIGINS", "")),
    }
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-csrftoken",
)

CSRF_TRUSTED_ORIGINS = sorted(
    {
        *CORS_ALLOWED_ORIGINS,
        *_split_env_origins(os.getenv("CSRF_TRUSTED_ORIGINS", "")),
    }
)

CSRF_COOKIE_SAMESITE = os.getenv(
    "CSRF_COOKIE_SAMESITE",
    "None" if not DEBUG else "Lax",
)
CSRF_COOKIE_SECURE = _env_flag("CSRF_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False

SESSION_COOKIE_SAMESITE = os.getenv(
    "SESSION_COOKIE_SAMESITE",
    "None" if not DEBUG else "Lax",
)
SESSION_COOKIE_SECURE = _env_flag("SESSION_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "").strip()
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "").strip()
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI", "").strip()
GOOGLE_ALLOWED_HOSTED_DOMAIN = os.getenv("GOOGLE_ALLOWED_HOSTED_DOMAIN", "").strip()
GOOGLE_ALLOWED_EMAILS = os.getenv("GOOGLE_ALLOWED_EMAILS", "").strip()
GOOGLE_DEFAULT_CARGO = os.getenv("GOOGLE_DEFAULT_CARGO", "").strip()
GOOGLE_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_ID", "primary").strip() or "primary"
GOOGLE_CALENDAR_TIMEZONE = (
    os.getenv("GOOGLE_CALENDAR_TIMEZONE", TIME_ZONE).strip() or TIME_ZONE
)
GOOGLE_TOKEN_ENCRYPTION_KEY = os.getenv("GOOGLE_TOKEN_ENCRYPTION_KEY", "").strip()
if not GOOGLE_TOKEN_ENCRYPTION_KEY and not DEBUG:
    raise ImproperlyConfigured(
        "Defina GOOGLE_TOKEN_ENCRYPTION_KEY nas variaveis de ambiente de producao "
        "(sem ela, tokens OAuth do Google seriam cifrados com uma chave derivada de SECRET_KEY)."
    )
GOOGLE_SYNC_PAST_DAYS = int(os.getenv("GOOGLE_SYNC_PAST_DAYS", "").strip() or "180")
GOOGLE_CALENDAR_WEBHOOK_URL = os.getenv("GOOGLE_CALENDAR_WEBHOOK_URL", "").strip()
GOOGLE_WATCH_RENEWAL_HOURS = int(
    os.getenv("GOOGLE_WATCH_RENEWAL_HOURS", "").strip() or "24"
)
GOOGLE_DRIVE_ROOT_FOLDER_ID = os.getenv("GOOGLE_DRIVE_ROOT_FOLDER_ID", "").strip()
DRIVE_MAX_FILE_SIZE_MB = int(os.getenv("DRIVE_MAX_FILE_SIZE_MB", "").strip() or "25")

DEMO_DATA_ENABLED = _env_flag("DEMO_DATA_ENABLED", default=False)

AI_PROVIDER = os.getenv("AI_PROVIDER", "openai").strip() or "openai"
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "").strip()
OPENAI_TRANSCRIPTION_MODEL = (
    os.getenv("OPENAI_TRANSCRIPTION_MODEL", "gpt-4o-transcribe").strip()
    or "gpt-4o-transcribe"
)
OPENAI_SUMMARY_MODEL = (
    os.getenv("OPENAI_SUMMARY_MODEL", "gpt-4.1-mini").strip() or "gpt-4.1-mini"
)
OPENAI_CLASSIFICATION_MODEL = (
    os.getenv("OPENAI_CLASSIFICATION_MODEL", "gpt-4.1-mini").strip() or "gpt-4.1-mini"
)
DRIVE_AI_MAX_OPERACOES = int(os.getenv("DRIVE_AI_MAX_OPERACOES", "").strip() or "100")
MEETINGS_MAX_AUDIO_SIZE_MB = int(
    os.getenv("MEETINGS_MAX_AUDIO_SIZE_MB", "").strip() or "25"
)

# Quando ligado, ao finalizar a reunião (gerar o documento no Drive com sucesso)
# os áudios da gravação são apagados do Drive. Desligado por padrão: o documento
# é sempre gerado, mas o áudio só é removido após validação do fluxo ponta a ponta.
MEETINGS_DELETE_AUDIO_AFTER_DOC = (
    os.getenv("MEETINGS_DELETE_AUDIO_AFTER_DOC", "").strip().lower()
    in ("1", "true", "yes", "on")
)

_REDIS_URL = os.getenv("REDIS_URL", "").strip()
CELERY_BROKER_URL = (
    os.getenv("CELERY_BROKER_URL", "").strip()
    or _REDIS_URL
    or ("redis://localhost:6379/0" if DEBUG else "")
)
CELERY_RESULT_BACKEND = (
    os.getenv("CELERY_RESULT_BACKEND", "").strip()
    or _REDIS_URL
    or ("redis://localhost:6379/0" if DEBUG else "")
)
MEETINGS_PROCESSING_MODE = os.getenv("MEETINGS_PROCESSING_MODE", "").strip().lower()
if not MEETINGS_PROCESSING_MODE:
    MEETINGS_PROCESSING_MODE = "celery" if CELERY_BROKER_URL else "inline"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Cache: Redis quando REDIS_URL/CACHE_URL existir, senão memória local (dev/test).
# KEY_PREFIX evita colisão com chaves do broker Celery na mesma instância Redis.
_CACHE_URL = os.getenv("CACHE_URL", "").strip() or _REDIS_URL
if _CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _CACHE_URL,
            "KEY_PREFIX": "juris",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Endurecimento HTTPS — habilitado em produção, configurável por env para não
# quebrar o desenvolvimento local em http.
SECURE_SSL_REDIRECT = _env_flag("SECURE_SSL_REDIRECT", default=not DEBUG)
SECURE_HSTS_SECONDS = int(
    os.getenv("SECURE_HSTS_SECONDS", "").strip() or (0 if DEBUG else "31536000")
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_flag(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG
)
SECURE_HSTS_PRELOAD = _env_flag("SECURE_HSTS_PRELOAD", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Logging: stdout é o canal correto em containers/VMs — o coletor da plataforma captura.
# Nível dos apps via LOG_LEVEL.
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG" if DEBUG else "INFO").strip().upper()
APP_LOGGERS = [
    "agenda",
    "clientes",
    "core",
    "documentos",
    "integrations",
    "meetings",
    "peticoes",
    "prazos",
    "processos",
    "productivity",
    "usuarios",
    "ai",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        **{
            name: {
                "handlers": ["console"],
                "level": LOG_LEVEL,
                "propagate": False,
            }
            for name in APP_LOGGERS
        },
    },
}
