# Generated by Django 6.0.3 on 2026-05-23 18:56

import django.db.models.deletion
import meetings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('processos', '0002_alter_processo_numero_processo_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_reuniao', models.DateTimeField(blank=True, null=True)),
                ('pauta', models.TextField(blank=True)),
                ('criado_por', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reunioes', to='clientes.cliente')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reunioes', to='processos.processo')),
            ],
            options={
                'ordering': ('-data_reuniao', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='Gravacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_audio', models.FileField(upload_to=meetings.models.recording_upload_path)),
                ('nome_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('transcribindo', 'Transcrevendo'), ('resumindo', 'Gerando resumo'), ('concluida', 'Concluída'), ('falhou', 'Falhou')], default='enviada', max_length=20)),
                ('transcricao', models.TextField(blank=True)),
                ('resumo', models.TextField(blank=True)),
                ('provedor', models.CharField(default='openai', max_length=30)),
                ('modelo_transcricao', models.CharField(blank=True, max_length=80)),
                ('modelo_resumo', models.CharField(blank=True, max_length=80)),
                ('erro_processamento', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('processamento_iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('processada_em', models.DateTimeField(blank=True, null=True)),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravacoes', to='meetings.reuniao')),
            ],
            options={
                'ordering': ('-criada_em',),
            },
        ),
    ]
