# Generated by Django 6.0.6 on 2026-06-11 05:53

import django.db.models.deletion
from django.db import migrations, models

import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_remove_reuniao_processo"),
        ("usuarios", "0007_remove_usuario_google_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gravacao",
            name="drive_file_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="gravacao",
            name="enviada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gravacoes_enviadas",
                to="usuarios.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="gravacao",
            name="arquivo_audio",
            field=models.FileField(
                blank=True, upload_to=meetings.models.recording_upload_path
            ),
        ),
    ]
