# Generated by Django 6.0.6 on 2026-06-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_gravacao_drive_file_id_gravacao_enviada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravacao',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='resumo',
            field=models.TextField(blank=True),
        ),
    ]
