# Generated by Django 6.0.6 on 2026-06-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_gravacao_ordem_reuniao_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='documento_drive_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='documento_gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='documento_link',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
