# Generated by Django 6.0.3 on 2026-03-28 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('clientes', '0001_initial'),
        ('processos', '0002_rename_numero_processo_numero_processo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Evento',
        ),
    ]
