# Generated by Django 6.0.6 on 2026-07-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_reconcile_google_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page_token', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_sync', to='integrations.googleaccount')),
            ],
        ),
    ]
