# Generated by Django 6.0.3 on 2026-04-15 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo_evento', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('prioridade', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=100)),
                ('criado_por', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('lembrete_em', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processo')),
            ],
        ),
    ]
