# Generated by Django 6.0.3 on 2026-05-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_evento_google_event_id'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='google_event_id',
        ),
    ]
