# Generated by Django 6.0.6 on 2026-07-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0009_evento_lembrete_enviado"),
        ("clientes", "0002_cliente_parceria"),
        ("processos", "0003_processo_data_ultima_movimentacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="processo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="processos.processo",
            ),
        ),
    ]
