# Generated by Django 6.0.6 on 2026-07-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_evento_cliente_alter_evento_processo'),
        ('clientes', '0005_cliente_clientes_cl_nome_b2cdde_idx_and_more'),
        ('processos', '0006_processo_advogado_habilitado'),
        ('usuarios', '0010_normalize_legacy_cargos'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data_inicio'], name='agenda_even_data_in_3a40c5_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['status'], name='agenda_even_status_b5b9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo_evento'], name='agenda_even_tipo_ev_846606_idx'),
        ),
    ]
