# Generated by Django 6.0.6 on 2026-07-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('prazo', 'Prazo'), ('evento', 'Evento'), ('reuniao', 'Reunião'), ('atribuicao', 'Atribuição'), ('sistema', 'Sistema')], max_length=20),
        ),
    ]
