# Generated by Codex on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="numero_processo",
            field=models.CharField(max_length=30),
        ),
    ]
