# Generated by Django 6.0.3 on 2026-03-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='numero',
            new_name='numero_processo',
        ),
    ]
