# Generated by Django 6.0.3 on 2026-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_rename_numero_processo_numero_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(max_length=40),
        ),
    ]
