# Generated by Django 6.0.3 on 2026-06-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0002_alter_processo_numero_processo_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="data_ultima_movimentacao",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
