# Generated by Django 6.0.6 on 2026-07-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_advogado_responsavel_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
