# Generated by Django 6.0.6 on 2026-07-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_alter_processo_numero_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='advogado_habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
