# Generated by Django 6.0.6 on 2026-07-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_clientes_cl_nome_b2cdde_idx_and_more'),
        ('processos', '0006_processo_advogado_habilitado'),
        ('usuarios', '0010_normalize_legacy_cargos'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['status'], name='processos_p_status_b5122a_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['area_juridica'], name='processos_p_area_ju_4481c0_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['vara'], name='processos_p_vara_b9125f_idx'),
        ),
    ]
