# Generated by Django 6.0.3 on 2026-04-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('tipo_cliente', models.CharField(choices=[('esporadico', 'Esporádico'), ('mensalista', 'Mensalista')], default='esporadico', max_length=20)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
    ]
