# Generated by Django 6.0.6 on 2026-06-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parceria',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
