# Generated by Django 6.0.6 on 2026-07-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('cpf',), name='cliente_cpf_unico_quando_preenchido'),
        ),
    ]
