# Generated by Django 6.0.3 on 2026-03-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('admin', 'Administrador'), ('advogado', 'Advogado'), ('estagiario', 'Estagiário')], max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_usuarios/')),
                ('OAB', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
