# Generated by Django 6.0.6 on 2026-06-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticoes', '0003_peticao_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticao',
            name='drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
