# Generated by Django 6.0.6 on 2026-07-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_clientes_cl_nome_b2cdde_idx_and_more'),
        ('financeiro', '0001_initial'),
        ('processos', '0006_processo_advogado_habilitado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['tipo'], name='financeiro__tipo_980071_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['categoria'], name='financeiro__categor_53c9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['status'], name='financeiro__status_959311_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_a4239e_idx'),
        ),
    ]
