# Generated by Django 6.0.3 on 2026-04-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('esporadico', 'Esporádico'), ('mensalista', 'Mensalista')], default='esporadico', max_length=20),
        ),
    ]
