# Generated by Django 6.0.6 on 2026-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prazos', '0002_migrate_eventos_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazo',
            name='drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prazo',
            name='link_drive',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
