# Generated by Django 6.0.6 on 2026-07-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prazos', '0004_responsavel_fk'),
        ('processos', '0006_processo_advogado_habilitado'),
        ('usuarios', '0010_normalize_legacy_cargos'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prazo',
            index=models.Index(fields=['status'], name='prazos_praz_status_626991_idx'),
        ),
        migrations.AddIndex(
            model_name='prazo',
            index=models.Index(fields=['data_limite'], name='prazos_praz_data_li_17d543_idx'),
        ),
    ]
