# Generated by Django 6.0.6 on 2026-07-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prazos', '0005_prazo_prazos_praz_status_626991_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazo',
            name='notificacao_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
