# Generated by Django 6.0.6 on 2026-07-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status_prospeccao',
            field=models.CharField(default='Em contato', max_length=50),
        ),
    ]
