# Generated by Codex on 2026-04-04

from django.db import migrations, models


def normalize_existing_cargos(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    mapping = {
        "admin": "Administrador",
        "advogado": "Advogado",
        "estagiario": "Estagiário",
    }

    for legacy_value, cargo_label in mapping.items():
        Usuario.objects.filter(cargo=legacy_value).update(cargo=cargo_label)


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cargo",
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(normalize_existing_cargos, migrations.RunPython.noop),
    ]
