# Generated by Codex on 2026-04-15

from django.db import migrations


def drop_legacy_usuario_columns(apps, schema_editor):
    table_name = "usuarios_usuario"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    for column_name in ("foto", "OAB"):
        if column_name in existing_columns:
            schema_editor.execute(
                "ALTER TABLE %s DROP COLUMN %s"
                % (
                    schema_editor.quote_name(table_name),
                    schema_editor.quote_name(column_name),
                )
            )


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(drop_legacy_usuario_columns, migrations.RunPython.noop),
    ]
