# Generated by Django 6.0.3 on 2026-04-16 08:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0002_cleanup_legacy_usuario_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(max_length=150),
        ),
    ]
