# Generated by Codex on 2026-04-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_cargo_dynamic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="OAB",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="foto",
        ),
    ]
