# Generated by Django 6.0.3 on 2026-04-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='OAB',
        ),
    ]
