# Generated by Django 6.0.3 on 2026-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_manual_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='google_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
