# Generated by Django 6.0.6 on 2026-07-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_fix_peticao_label_add_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='entidade_tipo',
            field=models.CharField(choices=[('processo', 'Processo'), ('prazo', 'Prazo'), ('peticao', 'Petição'), ('evento', 'Evento'), ('usuario', 'Usuário')], max_length=20),
        ),
    ]
