# Generated by Django 6.0.6 on 2026-06-10 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pasta_cliente_id", models.CharField(max_length=255)),
                ("pasta_peticoes_id", models.CharField(max_length=255)),
                ("pasta_documentos_id", models.CharField(max_length=255)),
                ("pasta_outros_id", models.CharField(max_length=255)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive",
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("petition", "Petição"),
                            ("document", "Documento"),
                            ("other", "Outro"),
                        ],
                        default="document",
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=150)),
                ("tamanho_bytes", models.PositiveBigIntegerField(default=0)),
                ("drive_file_id", models.CharField(max_length=255, unique=True)),
                ("drive_folder_id", models.CharField(max_length=255)),
                ("link_visualizacao", models.URLField(blank=True, max_length=1000)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ("cliente__nome", "categoria", "nome"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cliente", "categoria", "nome"),
                        name="documento_unico_por_cliente_categoria_nome",
                    )
                ],
            },
        ),
    ]
