# Generated by Django 6.0.6 on 2026-06-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientedrive',
            name='pasta_reunioes_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
