# Generated by Django 6.0.6 on 2026-06-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_parceria'),
        ('documentos', '0002_clientedrive_pasta_reunioes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaGerenciada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_drive_id', models.CharField(max_length=255)),
                ('drive_folder_id', models.CharField(max_length=255, unique=True)),
                ('ordem', models.PositiveIntegerField()),
                ('nome_base', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas_gerenciadas', to='clientes.cliente')),
            ],
            options={
                'ordering': ('parent_drive_id', 'ordem'),
            },
        ),
    ]
