# Generated by Django 6.0.6 on 2026-07-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_pastagerenciada"),
        ("processos", "0003_processo_data_ultima_movimentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentocliente",
            name="processo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos",
                to="processos.processo",
            ),
        ),
        migrations.CreateModel(
            name="ProcessoDrive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pasta_id", models.CharField(max_length=255)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "processo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive",
                        to="processos.processo",
                    ),
                ),
            ],
        ),
    ]
