# Generated by Django 6.0.7 on 2026-10-10 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documentocliente_processo_processodrive'),
        ('usuarios', '0010_normalize_legacy_cargos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenomeacaoPastaPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('processo', 'Processo')], max_length=20)),
                ('objeto_id', models.PositiveIntegerField()),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usuarios.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo', 'objeto_id'), name='unique_renomeacao_pasta_por_objeto')],
            },
        ),
    ]
